### ISSUE TITLE
Inference time issue

### ISSUE THREAD

**Issue by youngwanLEE** [gpleiss/efficient_densenet_pytorch#55]
Hi,

[The table](Speed (sec/mini batch)) shows comparison of speed(sec/mini bach). 

Is the speed a training time? 

I wonder whether the inference speed of efficient one is also slower than the naive implementation.

Did you compare the inference time, too?

**Comment by gpleiss** [comment]
Inference time is exactly the same. The efficient operations are only necessary for training. The efficient operations reduce the number of feature maps that are stored in memory. During inference, this is not an issue because feature maps are not stored during inference.

For more description, please read the tech report.
