### ISSUE TITLE
multi-GPU version slower with more GPUs

### ISSUE THREAD

**Issue by hongyi-zhang** [gpleiss/efficient_densenet_pytorch#9]
Hi, thanks for the implementation.

I find one weird thing using the multi-GPU option. I am trying to replicate the DenseNet-190-40 model which in the DenseNet paper produced the best result on CIFAR dataset. Using a minibatch size of 256, I can train with >= 4 GPUs but not with 2 GPUs, which indicates the multi-GPU version is working properly. However, I also find that per minibatch training time is about 30% slower with 8 GPUs vs. 4 GPUs. Is this expected and do you know what is slowing down the training?

Thanks!

**Comment by taineleau** [comment]
I guess the speed-down comes from the overhead of multi-GPU synchronization, which is a general issue across all deep learning platform. 

If you're using mini-batch size = 256 and 8 GPUs to train DenseNet, each GPU is not fully utilized (the utility is about 40%~50%). Also, the CIFAR dataset is sensitive to the mini-batch size, I feel you cannot reproduce the result if you are using 256 instead of 64.
